#! /bin/bash -x
./determinant_thread 4 1 
./determinant_thread 6 1 
./determinant_thread 8 2 
./determinant_thread 8 4 
./determinant_thread 8 6 
./determinant_thread 8 8 
./determinant_thread 10 4 
./determinant_thread 10 6 
./determinant_thread 10 8
./determinant_thread 12 4 
./determinant_thread 12 6 
./determinant_thread 12 8 
./determinant_thread 14 4 
./determinant_thread 14 6 
./determinant_thread 14 8 
./determinant_thread 16 4 
./determinant_thread 16 6 
./determinant_thread 16 8 

